### PR TITLE
feat/search by location

### PR DESCRIPTION
**Pull request by filwas**
In this PR I'm adding the feature of search by location. I've achieved this by generalising the previous iteration of Input element, which only searched for job title before. There were some design questions regarding how the autocomplete feature should differ from the job title autocomplete, but in the end I chose the simplest solution - otherwise, I'd have to create a distinct location filtering function, which doesn't seem to be needed in this project. 

Input element should be now general enough to be good to use in a different context in the app. 

Two more things I did in this PR are: added main/self-link to the "JO-BOARD" title in the upper-left corner of the app and got rid of some warnings by adding key attributes to the mapped Checkbox elements in the Filters component.

### CODE REVIEW

**Review by NerdbordMentor — APPROVED** [review]
## Code Review Report

### Task goal
We should be able to filter job offers by value in `Search location` autosuggestion input

### Requirements
1. UI should be implemented as in [design](https://www.figma.com/file/2f23T1l0pY13cBgsEyL5es/Nerdbord-x-Joboard?node-id=2722-8556&t=HXGyDxdzTDuSZZLS-4)
2. When typing inside the input, job offers should filter dynamically for matching **location** records. Matched records **should include typed value**
3. When typing value into search input, autosuggestion list should show, and list all potential records that could match. **It should only suggest available job offer locations.**
4. Clicking on suggestion should set input value

### Code changes review

#### src/App.module.scss
The changes in this file are not related to the task requirements. It seems like a new style was added for a main link, but it's not part of the task.

#### src/App.tsx
The changes in this file are not related to the task requirements. It seems like a link was added to the main title, but it's not part of the task.

#### src/components/Filters/Filters.tsx
The changes in this file are not related to the task requirements. It seems like the code was refactored to improve readability and maintainability, but it doesn't affect the functionality related to the task.

#### src/components/JobOffers/JobOffersScreen.tsx
The changes in this file are related to the task requirements. A new function `handleClickAutocomplete` was added and passed to the `Input` components. This function updates the filter settings when an autosuggestion is clicked, which is part of the task requirements.

#### src/components/UI/Input.tsx
The changes in this file are related to the task requirements. The `Input` component was updated to show autosuggestions for the location input and to call the `handleClickAutocomplete` function when an autosuggestion is clicked. This meets the task requirements.

### Conclusion
The code changes cover the task requirements. The autosuggestion input for the location was implemented and it filters job offers dynamically. The autosuggestion list shows potential matching records and clicking on a suggestion sets the input value. However, there were also changes that are not related to the task requirements.

**Review by meczajkowski — CHANGES_REQUESTED** [review]
There is a bug when you type one letter  into location input, it displays positions instead of locations

image

**Comment by filwas** [comment]
> There is a bug when you type one letter into location input, it displays positions instead of locations
> 

Can you double check or find a way to reproduce this? "U mnie dziala" ;P 

image

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### src/App.module.scss
No issues found in the changes. The added styles for `.mainLink` and its hover state are not directly related to the task requirements but do not introduce any bugs.

### src/App.tsx
The change wraps the "👾 JO-BOARD" text in an anchor tag with a `className` of `styles.mainLink`. This change is not related to the task requirements and does not contribute to the filter functionality.

### src/components/Filters/Filters.tsx
The changes in this file are primarily code formatting and adding `key` props to the list items, which is good practice in React but does not address the task requirements of filtering job offers by location.

### src/components/JobOffers/JobOffersScreen.tsx
The changes include refactoring and adding a new function `handleClickAutocomplete`. This function updates the filter based on the selected suggestion from the autosuggestion list, which aligns with the requirement that clicking on a suggestion should set the input value.

### src/components/UI/Input.tsx
The changes in this file are significant and directly related to the task requirements:

1. The `handleInput` function has been renamed to `internalInputHandler` and now calls `props.handleInput`. This change does not affect functionality.
2. A new `keyPressHandler` function has been added to handle keyboard events, setting the focus state to false when Enter or Escape is pressed. This is not a direct requirement but improves UX.
3. The `onClickHandler` sets the focus state to true when the input is clicked, which is good for UX but not a direct requirement.
4. The `internalClickAutocompleteHandler` function calls `props.handleClickAutocomplete`, which is used to update the filter when an autosuggestion is clicked. This is a requirement.
5. The `handleMouseEnterAutocomplete` and `handleMouseLeaveAutocomplete` functions improve UX by changing the background color of suggestions on hover but are not required by the task.
6. The rendering of suggestions has been updated to display either the job title or location based on the input type, which is a requirement for showing location suggestions.

### Summary
The changes partially cover the task requirements. The implementation of autosuggestion functionality in the `Input.tsx` component and handling clicks on suggestions in `JobOffersScreen.tsx` align with the requirements. However, there are some missing elements:

- The task requires that job offers should filter dynamically for matching location records as the user types. While there is an autosuggestion feature implemented, it's unclear if the actual job offers displayed on the page are filtered based on the input value. This dynamic filtering logic should be reviewed in the context of how job offers are rendered on the page.
- The requirement that autosuggestion should only suggest available job offer locations is partially met. The code suggests locations based on input, but there's no explicit check to ensure that only available job offer locations are suggested. This might require additional logic to filter out unique locations from the job offers data before rendering suggestions.
- There's no evidence of UI implementation according to the provided design link. This would require a visual comparison with the design specifications, which is not possible within this review context.

To fully meet the task requirements, ensure that:
- Dynamic filtering of job offers based on location input is implemented and tested.
- Autosuggestions are limited to available job offer locations.
- UI elements match the provided design specifications.

Here's an example of how you might implement dynamic filtering for job offers based on location input:

```javascript
// In JobOffersScreen.tsx or a similar component responsible for rendering job offers

const filteredOffers = data.filter(offer => {
  return offer.location.toLowerCase().includes(filterSettings.locationString.toLowerCase());
});

// ...then use 'filteredOffers' to render the list of job offers
```

This code assumes that `data` is an array of job offers and that `filterSettings.locationString` contains the user's input for location filtering.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### src/App.module.scss
No issues found. The changes are styling related and do not impact the functionality required by the task.

### src/App.tsx
No issues found. The changes are related to wrapping the title in a link, which is not related to the task requirements.

### src/components/Filters/Filters.tsx
The changes in this file are mostly about adding `key` props to the list items and improving the formatting of the code. However, these changes do not relate to the task requirements of implementing a filter by value in the "Search location" autosuggestion input.

### src/components/JobOffers/JobOffersScreen.tsx
The changes include refactoring and adding a new function `handleClickAutocomplete`. This function seems to be intended for handling clicks on autosuggestion items, which aligns with the task requirement that clicking on a suggestion should set the input value. However, without seeing the implementation of `updateFilter`, it's not possible to confirm if this indeed sets the input value correctly.

### src/components/UI/Input.tsx
Significant changes have been made here, which seem to be aimed at implementing the autosuggestion feature:

1. A new state `uniqueCities` and an effect hook have been added to filter unique city names from job offers. This aligns with the requirement that the autosuggestion list should only suggest available job offer locations.

2. The `renderHighlightedResult` function has been introduced to highlight matched parts of the autosuggestion results, which aligns with the requirement that matched records should include the typed value.

3. Event handlers for keyboard navigation (`keyPressHandler`), clicking (`onClickHandler`), and mouse events on autosuggestion items (`handleMouseEnterAutocomplete` and `handleMouseLeaveAutocomplete`) have been added. These changes are related to UI interactions but do not directly impact the core functionality required by the task.

4. The `internalClickAutocompleteHandler` function has been added to handle clicks on autosuggestion items, which is a requirement of the task.

5. The `internalInputHandler` function wraps `props.handleInput` to handle input events, which should contribute to filtering job offers dynamically based on the input value.

6. The autosuggestion list is conditionally rendered based on whether the input is focused and has a non-empty value, which is a partial implementation of the requirement that typing into the search input should show an autosuggestion list.

### Summary
The code changes partially cover the task requirements. The implementation of unique city filtering for autosuggestions and handling clicks on suggestions seems to be in place. However, there are a few concerns:

- It's unclear how `updateFilter` is implemented; thus, it's not possible to confirm if selecting an autosuggestion sets the input value correctly.
- Dynamic filtering of job offers based on the "Search location" input is not explicitly shown in the diffs provided.
- There is no implementation detail provided for how typing in the input dynamically filters job offers for matching location records, which is a core requirement of the task.

To fully meet the task requirements, ensure that typing in the "Search location" input dynamically filters job offers and that selecting an autosuggestion sets the input value correctly. If `updateFilter` is responsible for updating the state that filters job offers, it should be reviewed to ensure it meets this requirement.

**Comment by filwas** [comment]
Nerdy, you're crazy!

**Review by NerdbordMentor — APPROVED** [review]
Force approved. Hope you're not cheating!

**Pull request merged**
